api is what broke it
When I used the fetch.js api it broke the deployment due to:
```
Error: EEXIST: file already exists, symlink 'en/about.func' -> '/home/runner/work/org/org/.vercel/output/functions/en.func'```

Removing the fetch.js file fixed the issue. Now to see if it's the
existence of the API file at all or if it's something special within the
file.